business_mapping = {
    'Restaurant': 1,
    'Bar/Pub': 2,
    'Restaurant and Bar': 3,
    'Nightclub': 4,
    'Shop': 5,
    'Laundromat': 6,
    'Office': 7,
    'Massage Establishment': 8,
    'Medical Clinic': 9,
    'Pet Shop': 10,
    'Pet Boarding': 11,
    'Commercial School': 12,
    'Childcare Centre': 13,
    'Fitness Centre/Gymnasium': 14,
    'Amusement Centre': 15,
    'Residential': 16,
    "Backpackers' Hostel": 17,
    'Hotel': 18,
    "Students' Hostel": 19,
    'Serviced Apartment': 20,
    "Workers' Dormitories": 21,
    'Light Industrial Use': 22,
    'General Industrial Use': 23,
    'Industrial Training': 24,
    'Warehouse': 25,
    'Industrial Canteen': 26,
    'Showroom': 27,
    'E-business': 28,
    'Core Media Activities': 29,
    'Association/Community Club/Family Service Centre': 30,
    'Religious Activities': 31,
    'Limited & Non-Exclusive Religious Use': 32
}

classification_mapping = {
    1: "No Planning Permission Required",
    2: "Instant Approval",
    3: "Submit Change Of Use Application For Evaluation",
    4: "Not Allowed"
}
